"""Standardised command-line interfaces to scripts."""

import argparse
import json
from datetime import datetime
from logging import FileHandler, Logger
from pathlib import Path
from typing import Any


class SimulationCLI(argparse.ArgumentParser):
    """Command-line interface for simulation scripts."""

    _default_checkpoint_path: str
    _default_output_dir: str

    is_profiling: bool
    log_path: Path | None
    place_all_outputs_under: Path
    sim_name: str

    def __init__(
        self,
        *args,
        profiling_option: bool = False,
        sim_name: str = "simulation",
        place_all_outputs_under: Path | str = "outputs",
        description: str = "Simulate glitch on the boundary of a spherical star",
        **kwargs,
    ) -> None:
        """
        Assemble CLI for the simulation.

        `*args` and `**kwargs` are forwarded to `argparse.ArgumentParser`.

        :param profiling_option: Adds the `--profile` option to the CLI, allowing for
            profiling runs.
        :param sim_name: Name for the simulation, which is used when creating default
            directories if no explicit alternative is given.
        :param place_all_outputs_under: Directory under which to place all output files.
            Arguments like `--output_dir` will be interpreted as relative to this
            directory.
        :param description: Description for the CLI interface for the script. Passed to
            `argparse.ArgumentParser`.
        """
        kwargs["description"] = description
        super().__init__(*args, **kwargs)

        self.log_path = None
        self.place_all_outputs_under = Path(place_all_outputs_under)
        self.sim_name = str(sim_name)
        self._default_output_dir = self._default_dir_name()
        # Should this be auto-generated by the class, like _default_output_dir?
        self._default_checkpoint_path = "checkpoints/checkpoints_sNumber.h5"

        self._add_standard_args()

        if profiling_option:
            self.is_profiling = True
            self.add_profiling_options(is_profiling=profiling_option)
        else:
            self.is_profiling = False

    def _add_standard_args(self) -> None:
        """Add arguments that all simulation CLIs accept to the instance."""
        self.add_argument(
            "--use_checkpoint",
            type=bool,
            default=False,
            help="Boolean argument to determine if to use a checkpoint file.",
        )
        self.add_argument(
            "--checkpoint_path",
            type=str,
            default=str(self.place_all_outputs_under / self._default_checkpoint_path),
            help="Path to the checkpoint file you want to use.",
        )
        self.add_argument(
            "--output_dir",
            type=str,
            default=None,
            help="Directory to store simulation outputs",
        )
        self.add_argument(
            "--parameter_file",
            type=Path,
            default=None,
            help="relative path to parameter file to use for this run, saved in"
            " json format.",
        )
        self.add_argument(
            "--logfile",
            type=str,
            default=None,
            help="Name of logfile, if you want to create one.",
        )

    def _default_dir_name(self) -> str:
        """Generate a default name for an output directory."""
        return (
            self.sim_name + "_" + datetime.now().astimezone().strftime("%Y-%m-%d-%H:%M")
        )

    def add_profiling_options(self, *, is_profiling: bool) -> None:
        """Add profiling option to CLI, if applicable."""
        if is_profiling:
            self.is_profiling = True
            self.add_argument(
                "--profile",
                default=None,
                type=str,
                help="Output directory for profiling results.",
            )
        else:
            self.is_profiling = False

    def parse_args_and_get_params(
        self,
        logger: Logger,
        *args,
        default_params: dict[str, Any] | None = None,
        **kwargs,
    ) -> dict[str, Any]:
        """
        Parse arguments, handle processing logic, and return simulation parameters.

        Note that the input `logger` will be edited by this method, having a handler
        added to the given instance in the event a `logfile` was specified.

        `*args` and `**kwargs` are forwarded to `argparse.ArgumentParser.parse_args()`.

        :param logger: Logger instance that is handling main simulation.
        :param default_params: Defaults to use for simulation parameters, if
            no `--parameter_file` was provided.
        :returns params: Parameter values loaded into a dictionary.
        """
        parsed_args: dict[str, Any] = vars(self.parse_args(*args, **kwargs))

        if parsed_args["parameter_file"] is not None:
            with Path.open(parsed_args["parameter_file"]) as param_file:
                params = json.load(param_file)
        elif default_params:
            params = dict(default_params)
        else:
            params = {}

        params["use_checkpoint"] = parsed_args["use_checkpoint"]
        params["checkpoint_path"] = parsed_args["checkpoint_path"]
        params["profile"] = parsed_args.get("profile")

        params["output_dir"] = self.place_all_outputs_under / (
            parsed_args["output_dir"]
            if parsed_args["output_dir"] is not None
            else self._default_output_dir
        )

        if parsed_args.get("logfile"):
            self.log_path = params["output_dir"] / f"{parsed_args['logfile']}.txt"
            self.log_path.parent.mkdir(exist_ok=True, parents=True)
            logger.addHandler(FileHandler(self.log_path))

        return params


def create_parser_analysis() -> argparse.ArgumentParser:
    """Create parser for command line arguments in plotting code."""
    parser = argparse.ArgumentParser(
        description="Full analysis of a single component spin up simulation"
    )
    parser.add_argument(
        "--parameter_file",
        type=str,
        default=None,
        help="relative path to parameter file to use for this run,"
        " saved in json format.",
    )

    parser.add_argument(
        "output_dir", type=str, default=None, help="Path to output directory."
    )

    parser.add_argument(
        "--fig_dir",
        type=str,
        default="outputs",
        help="The directory in which to save figures.",
    )

    parser.add_argument(
        "--frame_dir",
        type=str,
        default="frames",
        help="The directory in which to save frames.",
    )

    parser.add_argument(
        "--targets",
        type=float,
        nargs="*",
        default=[0.5, 0.6, 0.7, 0.8, 0.9],
        help="The coordinate values you want to plot against time (The default "
        "assumes you are plotting different radii against time).",
    )

    parser.add_argument(
        "--coordinate",
        type=str,
        default="r",
        help="The coordinate to compare the spin up with time against "
        "(ie vary the radial or angular location)."
        " Takes r by default, pass theta to vary the meridional coordinate instead.",
    )

    parser.add_argument(
        "--times_plot",
        type=float,
        nargs="*",
        default=[0.5, 4, 20],
        help="Three values of time to plot angular velocity at.",
    )

    return parser
